ALTER TABLE "attachments" ADD COLUMN "project_id" uuid;
ALTER TABLE "attachment_uploads" ADD COLUMN "project_id" uuid;
UPDATE "attachments" SET "project_id" = "notes"."project_id" FROM "notes" WHERE "notes"."id" = "attachments"."note_id";
UPDATE "attachment_uploads" SET "project_id" = "notes"."project_id" FROM "notes" WHERE "notes"."id" = "attachment_uploads"."note_id";
ALTER TABLE "attachments" ALTER COLUMN "project_id" SET NOT NULL;
ALTER TABLE "attachment_uploads" ALTER COLUMN "project_id" SET NOT NULL;
ALTER TABLE "attachments" ALTER COLUMN "note_id" DROP NOT NULL;
ALTER TABLE "attachment_uploads" ALTER COLUMN "note_id" DROP NOT NULL;
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE cascade;
ALTER TABLE "attachment_uploads" ADD CONSTRAINT "attachment_uploads_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE cascade;
DROP INDEX "attachments_note_path_unique";
CREATE UNIQUE INDEX "attachments_note_path_unique" ON "attachments" ("note_id", "path") WHERE "note_id" IS NOT NULL;
CREATE UNIQUE INDEX "attachments_project_path_unique" ON "attachments" ("project_id", "path") WHERE "note_id" IS NULL;
CREATE INDEX "attachments_project_idx" ON "attachments" ("project_id");
ALTER TABLE "attachment_versions" ADD COLUMN "processing_status" text NOT NULL DEFAULT 'queued';
ALTER TABLE "attachment_versions" ADD COLUMN "processing_failure" text;
ALTER TABLE "attachment_versions" ADD COLUMN "processed_at" timestamptz;
UPDATE "attachment_versions" SET "processing_status" = CASE WHEN "parser_kind" IS NULL THEN 'unsupported' ELSE 'ready' END, "processed_at" = "created_at";
ALTER TABLE "search_chunks" DROP CONSTRAINT "search_chunks_single_source";
ALTER TABLE "search_chunks" ADD COLUMN "attachment_id" uuid REFERENCES "attachments"("id") ON DELETE cascade;
ALTER TABLE "search_chunks" ADD COLUMN "attachment_path" text;
CREATE INDEX "search_chunks_attachment_idx" ON "search_chunks" ("attachment_id");
ALTER TABLE "search_chunks" ADD CONSTRAINT "search_chunks_single_source" CHECK (num_nonnulls("note_id", "memory_entry_id", "attachment_id") = 1);
