import type { AgentToolName } from '$lib/models/agent/tool-catalog';
import type { EntityKind } from '$lib/models/tool-display';

export type ToolFamily =
	'none' | 'link' | 'collection' | 'file-output' | 'record' | 'created' | 'lifecycle' | 'proposal';

/** Every built-in tool explicitly chooses a presentation. */
const catalog: Record<AgentToolName, { readonly family: ToolFamily; readonly kind: EntityKind }> = {
	get_project: { family: 'link', kind: 'project' },
	create_project: { family: 'created', kind: 'project' },
	rename_project: { family: 'record', kind: 'project' },
	archive_project: { family: 'lifecycle', kind: 'project' },
	create_folder: { family: 'created', kind: 'folder' },
	move_project_entry: { family: 'record', kind: 'note' },
	get_note: { family: 'link', kind: 'note' },
	create_note: { family: 'link', kind: 'note' },
	save_note: { family: 'link', kind: 'note' },
	edit_note: { family: 'link', kind: 'note' },
	rename_note: { family: 'record', kind: 'note' },
	archive_note: { family: 'lifecycle', kind: 'note' },
	restore_note: { family: 'lifecycle', kind: 'note' },
	delete_note_forever: { family: 'lifecycle', kind: 'note' },
	empty_note_trash: { family: 'lifecycle', kind: 'note' },
	list_note_versions: { family: 'collection', kind: 'plain' },
	restore_note_version: { family: 'link', kind: 'note' },
	publish_note: { family: 'link', kind: 'note' },
	discard_note_draft: { family: 'link', kind: 'note' },
	create_todo: { family: 'created', kind: 'todo' },
	create_todos: { family: 'created', kind: 'todo' },
	update_todo: { family: 'record', kind: 'todo' },
	extract_promises: { family: 'proposal', kind: 'plain' },
	relate_selection: { family: 'proposal', kind: 'plain' },
	revise_mermaid_diagram: { family: 'record', kind: 'diagram' },
	promote_diagram: { family: 'proposal', kind: 'diagram' },
	accept_suggestion: { family: 'record', kind: 'suggestion' },
	reject_suggestion: { family: 'record', kind: 'suggestion' },
	revert_suggestion: { family: 'record', kind: 'suggestion' },
	save_skill: { family: 'link', kind: 'skill' },
	edit_skill: { family: 'link', kind: 'skill' },
	create_skill: { family: 'link', kind: 'skill' },
	create_skill_from_selection: { family: 'link', kind: 'skill' },
	restore_skill_version: { family: 'link', kind: 'skill' },
	update_skill: { family: 'record', kind: 'skill' },
	set_skill_pinned: { family: 'record', kind: 'skill' },
	propose_memory_change: { family: 'proposal', kind: 'memory' },
	export_document: { family: 'created', kind: 'artifact' },
	create_diagram: { family: 'link', kind: 'diagram' },
	edit_diagram: { family: 'link', kind: 'diagram' },
	update_export_settings: { family: 'record', kind: 'setting' },
	download_artifact: { family: 'link', kind: 'artifact' },
	delete_artifact: { family: 'lifecycle', kind: 'artifact' },
	regenerate_artifact: { family: 'created', kind: 'artifact' },
	search: { family: 'collection', kind: 'note' },
	search_note: { family: 'collection', kind: 'note' },
	ls: { family: 'file-output', kind: 'plain' },
	grep: { family: 'file-output', kind: 'plain' },
	sed: { family: 'file-output', kind: 'plain' },
	search_icons: { family: 'collection', kind: 'plain' },
	find_references: { family: 'proposal', kind: 'plain' },
	get_today_view: { family: 'collection', kind: 'todo' },
	get_artifact: { family: 'link', kind: 'artifact' },
	get_export_settings: { family: 'record', kind: 'setting' },
	diff_note_versions: { family: 'link', kind: 'note' },
	read_canvas_diagram: { family: 'link', kind: 'diagram' },
	read_project_diagram: { family: 'link', kind: 'diagram' },
	list_projects: { family: 'collection', kind: 'project' },
	list_todos: { family: 'collection', kind: 'todo' },
	list_skills: { family: 'collection', kind: 'skill' },
	list_skill_versions: { family: 'collection', kind: 'plain' },
	list_artifacts: { family: 'collection', kind: 'artifact' },
	list_attachments: { family: 'collection', kind: 'attachment' },
	list_templates: { family: 'collection', kind: 'plain' },
	list_suggestions: { family: 'collection', kind: 'suggestion' },
	list_trashed_notes: { family: 'collection', kind: 'note' },
	list_user_memory: { family: 'collection', kind: 'memory' },
	list_project_memory: { family: 'collection', kind: 'memory' },
	search_tools: { family: 'collection', kind: 'plain' },
	get_workspace_context: { family: 'collection', kind: 'project' },
	load_skill: { family: 'link', kind: 'skill' },
	list_tool_preferences: { family: 'collection', kind: 'setting' },
	set_tool_enabled: { family: 'record', kind: 'setting' },
	list_agent_models: { family: 'collection', kind: 'plain' },
	get_agent_preferences: { family: 'record', kind: 'setting' },
	update_agent_preferences: { family: 'record', kind: 'setting' },
	list_trust_policies: { family: 'collection', kind: 'setting' },
	update_trust_policy: { family: 'record', kind: 'setting' },
	list_api_tokens: { family: 'collection', kind: 'plain' },
	revoke_api_token: { family: 'lifecycle', kind: 'setting' }
};

export const toolPresentationKind = (name: string) =>
	Object.hasOwn(catalog, name) ? catalog[name as AgentToolName] : undefined;
