import type { AgentToolName } from '$lib/models/agent/tool-catalog';
const labels: Record<AgentToolName, string> = {
	get_project: 'Read project',
	create_project: 'Create project',
	rename_project: 'Rename project',
	archive_project: 'Archive project',
	create_folder: 'Create folder',
	move_project_entry: 'Move',
	get_note: 'Read note',
	create_note: 'Create note',
	save_note: 'Save note',
	edit_note: 'Edit note',
	rename_note: 'Rename note',
	archive_note: 'Move note to trash',
	restore_note: 'Restore note',
	delete_note_forever: 'Delete note permanently',
	empty_note_trash: 'Empty trash',
	list_note_versions: 'Read note history',
	restore_note_version: 'Restore note version',
	publish_note: 'Publish note',
	discard_note_draft: 'Discard note draft',
	create_todo: 'Create todo',
	create_todos: 'Create todos',
	update_todo: 'Update todo',
	extract_promises: 'Find commitments',
	relate_selection: 'Link selection',
	revise_mermaid_diagram: 'Revise diagram',
	promote_diagram: 'Keep diagram',
	accept_suggestion: 'Accept suggestion',
	reject_suggestion: 'Dismiss suggestion',
	revert_suggestion: 'Undo suggestion',
	save_skill: 'Save skill',
	edit_skill: 'Edit skill',
	create_skill: 'Create skill',
	create_skill_from_selection: 'Create skill from selection',
	restore_skill_version: 'Restore skill version',
	update_skill: 'Update skill',
	set_skill_pinned: 'Change skill pinning',
	propose_memory_change: 'Remember',
	export_document: 'Export document',
	create_diagram: 'Create diagram',
	edit_diagram: 'Edit diagram',
	update_export_settings: 'Update export settings',
	download_artifact: 'Prepare download',
	delete_artifact: 'Delete artifact',
	regenerate_artifact: 'Regenerate artifact',

	// Quiet in the turn summary, but the log still names every one of them.
	search: 'Search',
	search_note: 'Search within a note',
	ls: 'List files',
	grep: 'Search notes and files',
	sed: 'Read file excerpt',
	search_icons: 'Search icons',
	find_references: 'Find references',
	get_today_view: "Read today's work",
	get_artifact: 'Read artifact',
	get_export_settings: 'Read export settings',
	diff_note_versions: 'Compare note versions',
	read_canvas_diagram: 'Read canvas diagram',
	read_project_diagram: 'Read diagram',
	list_projects: 'List projects',
	list_todos: 'List todos',
	list_skills: 'List skills',
	list_skill_versions: 'List skill versions',
	list_artifacts: 'List artifacts',
	list_attachments: 'List attachments',
	list_templates: 'List templates',
	list_suggestions: 'List suggestions',
	list_trashed_notes: 'List trashed notes',
	list_user_memory: 'Read profile memory',
	list_project_memory: 'Read project memory',

	// Mechanism: the agent finding its footing, named all the same.
	search_tools: 'Look up available tools',
	get_workspace_context: 'Read workspace context',
	load_skill: 'Read skill',
	list_tool_preferences: 'Read tool availability',
	set_tool_enabled: 'Change tool availability',
	list_agent_models: 'List available models',
	get_agent_preferences: 'Read agent settings',
	update_agent_preferences: 'Change agent settings',
	list_trust_policies: 'Read trust policies',
	update_trust_policy: 'Change trust policy',
	list_api_tokens: 'List access tokens',
	revoke_api_token: 'Revoke access token'
};

const completedLabels: Record<AgentToolName, string> = {
	get_project: 'Read project',
	create_project: 'Created project',
	rename_project: 'Renamed project',
	archive_project: 'Archived project',
	create_folder: 'Created folder',
	move_project_entry: 'Moved',
	get_note: 'Read note',
	create_note: 'Created note',
	save_note: 'Saved note',
	edit_note: 'Edited note',
	rename_note: 'Renamed note',
	archive_note: 'Moved note to trash',
	restore_note: 'Restored note',
	delete_note_forever: 'Deleted note permanently',
	empty_note_trash: 'Emptied trash',
	list_note_versions: 'Read note history',
	restore_note_version: 'Restored note version',
	publish_note: 'Published note',
	discard_note_draft: 'Discarded note draft',
	create_todo: 'Created todo',
	create_todos: 'Created todos',
	update_todo: 'Updated todo',
	extract_promises: 'Found commitments',
	relate_selection: 'Proposed links',
	revise_mermaid_diagram: 'Revised diagram',
	promote_diagram: 'Proposed keeping diagram',
	accept_suggestion: 'Accepted suggestion',
	reject_suggestion: 'Dismissed suggestion',
	revert_suggestion: 'Undid suggestion',
	save_skill: 'Saved skill',
	edit_skill: 'Edited skill',
	create_skill: 'Created skill',
	create_skill_from_selection: 'Created skill from selection',
	restore_skill_version: 'Restored skill version',
	update_skill: 'Updated skill',
	set_skill_pinned: 'Changed skill pinning',
	propose_memory_change: 'Proposed memory change',
	export_document: 'Exported document',
	create_diagram: 'Created diagram',
	edit_diagram: 'Edited diagram',
	update_export_settings: 'Updated export settings',
	download_artifact: 'Prepared download',
	delete_artifact: 'Deleted artifact',
	regenerate_artifact: 'Regenerated artifact',

	// Quiet in the turn summary, but the log still names every one of them.
	search: 'Searched',
	search_note: 'Searched within a note',
	ls: 'Listed files',
	grep: 'Searched notes and files',
	sed: 'Read file excerpt',
	search_icons: 'Searched icons',
	find_references: 'Found references',
	get_today_view: "Read today's work",
	get_artifact: 'Read artifact',
	get_export_settings: 'Read export settings',
	diff_note_versions: 'Compared note versions',
	read_canvas_diagram: 'Read canvas diagram',
	read_project_diagram: 'Read diagram',
	list_projects: 'Listed projects',
	list_todos: 'Listed todos',
	list_skills: 'Listed skills',
	list_skill_versions: 'Listed skill versions',
	list_artifacts: 'Listed artifacts',
	list_attachments: 'Listed attachments',
	list_templates: 'Listed templates',
	list_suggestions: 'Listed suggestions',
	list_trashed_notes: 'Listed trashed notes',
	list_user_memory: 'Read profile memory',
	list_project_memory: 'Read project memory',

	// Mechanism: the agent finding its footing, named all the same.
	search_tools: 'Looked up available tools',
	get_workspace_context: 'Read workspace context',
	load_skill: 'Read skill',
	list_tool_preferences: 'Read tool availability',
	set_tool_enabled: 'Changed tool availability',
	list_agent_models: 'Listed available models',
	get_agent_preferences: 'Read agent settings',
	update_agent_preferences: 'Changed agent settings',
	list_trust_policies: 'Read trust policies',
	update_trust_policy: 'Changed trust policy',
	list_api_tokens: 'Listed access tokens',
	revoke_api_token: 'Revoked access token'
};

export const isCatalogTool = (name: string): name is AgentToolName => name in labels;

/**
 * The reader's name for a tool.
 *
 * The un-snake-casing survives for exactly one case: a name we have genuinely
 * never seen — an MCP tool from another host. It is no longer how the app's own
 * catalogue renders, which is what it had quietly become.
 */
export const friendlyToolLabel = (name: string): string =>
	isCatalogTool(name)
		? labels[name]
		: name
				.split('_')
				.map((part, index) => (index === 0 ? part.charAt(0).toUpperCase() + part.slice(1) : part))
				.join(' ');

export const completedToolLabel = (name: string): string =>
	isCatalogTool(name) ? completedLabels[name] : `${friendlyToolLabel(name)} completed`;
