import { InMemoryNoteMarkdownReader } from '$lib/testing/notes/fakes/markdown-reader';
import { InMemoryDocumentRenderer } from '$lib/testing/deliverables/fakes/document-renderer';
import { TodoBoardExportService } from '$lib/services/todos/board-export';
import { TodoPresentationService } from '$lib/services/todos/presentation';
import { TodoEditingRulesService } from '$lib/services/todos/edits';
import { describe, expect, it } from 'vitest';
import { Todos, type TodosDependencies } from './controller';
import { ExportPreparationService } from '$lib/services/deliverables/export-preparation';
const preparation = new ExportPreparationService();
import { capabilityDependencies } from '$lib/testing/workspace/fakes/dependency-builder';
type BoardPdfGenerator = TodosDependencies['pdfGenerator']['render'];
type MarkdownToDocument = TodosDependencies['markdownToContent']['read'];
import { InMemoryTodos } from '$lib/testing/todos/fakes/in-memory-todos';
import { InMemoryProjects } from '$lib/testing/projects/fakes/in-memory-projects';
import {
	projectBuilder,
	testActor,
	testProjectId,
	testNow,
	testTodoId,
	todoBuilder
} from '$lib/testing/workspace/fixtures/domain-builders';

const setup = () => {
	const todos = new InMemoryTodos();
	const projects = new InMemoryProjects();
	const markdownSources: string[] = [];
	const markdownToDocument: MarkdownToDocument = (source) => {
		markdownSources.push(source);
		return { document: { type: 'doc' }, plainText: source };
	};
	const pdfInputs: Parameters<BoardPdfGenerator>[0][] = [];
	const pdfGenerator: BoardPdfGenerator = async (input) => {
		pdfInputs.push(input);
		return Buffer.from('pdf-bytes');
	};
	const service = new Todos(
		capabilityDependencies<TodosDependencies>({
			boardExport: new TodoBoardExportService(),
			todoPresentation: new TodoPresentationService(),
			todoEditingRules: new TodoEditingRulesService(),
			todoCreationRules: new TodoEditingRulesService(),
			todoLister: todos,
			todoContextReader: todos,
			projectLister: projects,
			markdownToContent: new InMemoryNoteMarkdownReader(markdownToDocument),
			exportPreparer: preparation,
			pdfGenerator: new InMemoryDocumentRenderer(pdfGenerator)
		})
	);
	return { todos, projects, markdownSources, pdfInputs, service };
};

describe('Board PDF export', () => {
	it.each([
		['missing', []],
		['archived', [projectBuilder({ archivedAt: testNow })]],
		['foreign', [projectBuilder({ userId: testActor(2).userId })]]
	])(
		'refuses a selected %s project instead of producing an all-projects export',
		async (_kind, rows) => {
			const { projects, service } = setup();
			projects.projects = rows;
			await expect(
				service.exportBoardPdf(testActor(), { projectId: testProjectId() })
			).rejects.toMatchObject({ code: 'NOT_FOUND' });
		}
	);
	it('builds the exported markdown from the listed todos', async () => {
		const { todos, markdownSources, service } = setup();
		todos.todos = [todoBuilder({ title: 'Send the design' })];
		await service.exportBoardPdf(testActor(), {});
		expect(markdownSources[0]).toContain('Send the design');
	});

	it('passes the filter through to the todo catalog', async () => {
		const { todos, projects, markdownSources, service } = setup();
		projects.projects = [projectBuilder()];
		todos.todos = [
			todoBuilder({ title: 'Kept' }),
			todoBuilder({ id: testTodoId(2), title: 'Filtered out', projectId: testProjectId(2) })
		];
		await service.exportBoardPdf(testActor(), { projectId: testProjectId() });
		expect(markdownSources[0]).not.toContain('Filtered out');
	});

	it('renders the export title on the first page', async () => {
		const { todos, pdfInputs, service } = setup();
		todos.todos = [todoBuilder()];
		await service.exportBoardPdf(testActor(), {});
		expect(pdfInputs[0]?.settings?.includeTitle).toBe(true);
	});

	it('returns the generated bytes as base64', async () => {
		const { todos, service } = setup();
		todos.todos = [todoBuilder({ title: 'Prepare review' })];
		const result = await service.exportBoardPdf(testActor(), {});
		expect({ filename: result.filename, data: result.data }).toEqual({
			filename: expect.stringMatching(/^kanban-all-\d{4}-\d{2}-\d{2}\.pdf$/),
			data: Buffer.from('pdf-bytes').toString('base64')
		});
	});

	it('names a project export after the resolved project', async () => {
		const { projects, service } = setup();
		projects.projects = [projectBuilder({ name: 'Apollo 11' })];
		const result = await service.exportBoardPdf(testActor(), { projectId: testProjectId() });
		expect(result.filename).toMatch(/^kanban-apollo-11-\d{4}-\d{2}-\d{2}\.pdf$/);
	});

	it('titles the document after the resolved project name', async () => {
		const { projects, pdfInputs, service } = setup();
		projects.projects = [projectBuilder({ name: 'Apollo 11' })];
		await service.exportBoardPdf(testActor(), { projectId: testProjectId() });
		expect(pdfInputs[0]?.title).toBe('Apollo 11 todos');
	});

	it('marks each card with its resolved project name', async () => {
		const { todos, projects, markdownSources, service } = setup();
		todos.todos = [todoBuilder()];
		projects.projects = [projectBuilder({ name: 'Apollo 11' })];
		await service.exportBoardPdf(testActor(), {});
		expect(markdownSources[0]).toContain('Apollo 11');
	});
});
