import { describe, expect, it } from 'vitest';
import { Todos, type BoardPdfGenerator, type TodosDependencies } from './controller';
import { InMemoryTodos } from '$lib/testing/todos/fakes/in-memory-todos';
import { InMemoryProjects } from '$lib/testing/projects/fakes/in-memory-projects';
import { capabilityDependencies } from '$lib/testing/workspace/fakes/dependency-builder';
import {
	projectBuilder,
	testActor,
	testProjectId,
	testTodoId,
	todoBuilder
} from '$lib/testing/workspace/fixtures/domain-builders';

const setup = () => {
	const todos = new InMemoryTodos();
	const projects = new InMemoryProjects();
	const pdfInputs: Parameters<BoardPdfGenerator>[0][] = [];
	const boardPdfGenerator: BoardPdfGenerator = async (input) => {
		pdfInputs.push(input);
		return Buffer.from('pdf-bytes');
	};
	const controller = new Todos(
		capabilityDependencies<TodosDependencies>({
			todoLister: todos,
			todoViewAssembler: todos,
			projectLister: projects,
			boardPdfGenerator
		})
	);
	return { todos, projects, pdfInputs, controller };
};

describe('Board PDF export', () => {
	it('builds the exported document from the listed todos', async () => {
		const { todos, pdfInputs, controller } = setup();
		todos.todos = [todoBuilder({ title: 'Send the design' })];
		await controller.exportBoardPdf(testActor(), {});
		expect(JSON.stringify(pdfInputs[0]?.notes[0]?.document)).toContain('Send the design');
	});

	it('passes the filter through to the todo catalog', async () => {
		const { todos, pdfInputs, controller } = setup();
		todos.todos = [
			todoBuilder({ title: 'Kept' }),
			todoBuilder({ id: testTodoId(2), title: 'Filtered out', projectId: testProjectId(2) })
		];
		await controller.exportBoardPdf(testActor(), { projectId: testProjectId() });
		expect(JSON.stringify(pdfInputs[0]?.notes[0]?.document)).not.toContain('Filtered out');
	});

	it('renders the export title on the first page', async () => {
		const { todos, pdfInputs, controller } = setup();
		todos.todos = [todoBuilder()];
		await controller.exportBoardPdf(testActor(), {});
		expect(pdfInputs[0]?.settings?.includeTitle).toBe(true);
	});

	it('returns the generated bytes as base64', async () => {
		const { controller } = setup();
		const result = await controller.exportBoardPdf(testActor(), {});
		expect(result.data).toBe(Buffer.from('pdf-bytes').toString('base64'));
	});

	it('names a cross-project export after the whole board', async () => {
		const { controller } = setup();
		const result = await controller.exportBoardPdf(testActor(), {});
		expect(result.filename).toMatch(/^kanban-all-\d{4}-\d{2}-\d{2}\.pdf$/);
	});

	it('names a project export after the resolved project', async () => {
		const { projects, controller } = setup();
		projects.projects = [projectBuilder({ name: 'Apollo 11' })];
		const result = await controller.exportBoardPdf(testActor(), { projectId: testProjectId() });
		expect(result.filename).toMatch(/^kanban-apollo-11-\d{4}-\d{2}-\d{2}\.pdf$/);
	});

	it('titles the document after the resolved project name', async () => {
		const { projects, pdfInputs, controller } = setup();
		projects.projects = [projectBuilder({ name: 'Apollo 11' })];
		await controller.exportBoardPdf(testActor(), { projectId: testProjectId() });
		expect(pdfInputs[0]?.title).toBe('Apollo 11 todos');
	});

	it('marks each card with its resolved project name', async () => {
		const { todos, projects, pdfInputs, controller } = setup();
		todos.todos = [todoBuilder()];
		projects.projects = [projectBuilder({ name: 'Apollo 11' })];
		await controller.exportBoardPdf(testActor(), {});
		expect(JSON.stringify(pdfInputs[0]?.notes[0]?.document)).toContain('Apollo 11');
	});
});
