import type { WorkspaceCommand } from '$lib/models/workspace-mutations';
import type { WorkspaceRecord } from '$lib/models/workspace-records';
import type { OutboxEntry } from '$lib/models/outbox';

export type WorkspaceWriteReviewEntry = OutboxEntry<WorkspaceCommand, WorkspaceRecord>;
export const writeAction: Record<WorkspaceCommand['kind'], string> = {
	renameConversation: 'Renamed chat',
	setToolPreference: 'Changed tool preference',
	setProjectToolOverride: 'Changed project tool preference',
	resetProjectToolOverride: 'Reset project tool preference',
	updateTrustPolicy: 'Changed approval policy',
	updateUserPreferences: 'Changed preferences',
	updateAgentPreferences: 'Changed agent preferences',
	updateExportSettings: 'Changed export settings',
	createMemory: 'Created memory',
	updateMemory: 'Edited memory',
	deleteMemory: 'Deleted memory',
	createProject: 'Created project',
	renameProject: 'Renamed project',
	archiveProject: 'Archived project',
	projectNumbering: 'Changed project numbering',
	createFolder: 'Created folder',
	createNote: 'Created note',
	updateSkill: 'Edited skill',
	renameNote: 'Renamed note',
	saveNote: 'Edited note',
	archiveNote: 'Archived note',
	restoreNote: 'Restored note',
	publishNote: 'Published note',
	discardNoteDraft: 'Discarded note draft',
	noteNumbering: 'Changed note numbering',
	createTodo: 'Created task',
	updateTodo: 'Edited task',
	deleteTodo: 'Deleted task',
	saveDiagram: 'Edited diagram',
	renameDiagram: 'Renamed diagram',
	publishDiagram: 'Published diagram',
	archiveDiagram: 'Archived diagram',
	restoreDiagram: 'Restored diagram',
	deleteDiagram: 'Deleted diagram'
};
/** Only product fields are rendered; identities, storage roles and bookkeeping stay out of review. */
export const reviewFieldLabels: Readonly<Record<string, string>> = {
	name: 'Name',
	title: 'Title',
	description: 'Description',
	content: 'Content',
	status: 'Status',
	priority: 'Priority',
	dueDate: 'Due date',
	responsibility: 'Responsibility',
	completed: 'Completed',
	isPinned: 'Pinned',
	isEnabled: 'Enabled',
	shareWithAgents: 'Share with agents',
	enabled: 'Enabled',
	language: 'Language',
	theme: 'Theme',
	numberingEnabled: 'Numbering',
	defaultModel: 'Default model',
	systemPrompt: 'Instructions',
	instructions: 'Instructions',
	fontFamily: 'Font',
	fontSize: 'Font size',
	pageSize: 'Page size',
	orientation: 'Orientation',
	preferences: 'Preferences',
	policy: 'Approval policy',
	mode: 'Mode',
	sectionNumbering: 'Section numbering',
	sectionNumberingDefault: 'Default section numbering',
	defaultVisionModel: 'Vision model',
	inlineModel: 'Suggestion model',
	attachmentVisionModel: 'Attachment vision model',
	webSearchEngine: 'Search engine',
	webSearchMaxResults: 'Results per search',
	webSearchMaxTotalResults: 'Total search results',
	agentMaxTurns: 'Agent turn limit',
	executionMode: 'Execution mode',
	inlineSuggestionsEnabled: 'Inline suggestions',
	toolName: 'Tool',
	pipeline: 'Workflow',
	autoAcceptEnabled: 'Automatic acceptance',
	minimumConfidence: 'Minimum confidence',
	settings: 'Export settings',
	archivedAt: 'Archived',
	slug: 'Address',
	dueAt: 'Due date',
	completedAt: 'Completed'
};
