import { describe, expect, it } from 'vitest';
import { BoardPdfExport, type BoardPdfGenerator, type MarkdownToDocument } from './board-export';
import { InMemoryTodos } from '$lib/testing/todos/fakes/in-memory-todos';
import { InMemoryProjects } from '$lib/testing/projects/fakes/in-memory-projects';
import {
	projectBuilder,
	testActor,
	testProjectId,
	testTodoId,
	todoBuilder
} from '$lib/testing/workspace/fixtures/domain-builders';

const setup = () => {
	const todos = new InMemoryTodos();
	const projects = new InMemoryProjects();
	const markdownSources: string[] = [];
	const markdownToDocument: MarkdownToDocument = (source) => {
		markdownSources.push(source);
		return { type: 'doc' };
	};
	const pdfInputs: Parameters<BoardPdfGenerator>[0][] = [];
	const pdfGenerator: BoardPdfGenerator = async (input) => {
		pdfInputs.push(input);
		return Buffer.from('pdf-bytes');
	};
	const service = new BoardPdfExport(todos, todos, projects, markdownToDocument, pdfGenerator);
	return { todos, projects, markdownSources, pdfInputs, service };
};

describe('Board PDF export', () => {
	it('builds the exported markdown from the listed todos', async () => {
		const { todos, markdownSources, service } = setup();
		todos.todos = [todoBuilder({ title: 'Send the design' })];
		await service.exportBoardPdf(testActor(), {});
		expect(markdownSources[0]).toContain('Send the design');
	});

	it('passes the filter through to the todo catalog', async () => {
		const { todos, markdownSources, service } = setup();
		todos.todos = [
			todoBuilder({ title: 'Kept' }),
			todoBuilder({ id: testTodoId(2), title: 'Filtered out', projectId: testProjectId(2) })
		];
		await service.exportBoardPdf(testActor(), { projectId: testProjectId() });
		expect(markdownSources[0]).not.toContain('Filtered out');
	});

	it('renders the export title on the first page', async () => {
		const { todos, pdfInputs, service } = setup();
		todos.todos = [todoBuilder()];
		await service.exportBoardPdf(testActor(), {});
		expect(pdfInputs[0]?.settings?.includeTitle).toBe(true);
	});

	it('returns the generated bytes as base64', async () => {
		const { service } = setup();
		const result = await service.exportBoardPdf(testActor(), {});
		expect(result.data).toBe(Buffer.from('pdf-bytes').toString('base64'));
	});

	it('names a cross-project export after the whole board', async () => {
		const { service } = setup();
		const result = await service.exportBoardPdf(testActor(), {});
		expect(result.filename).toMatch(/^kanban-all-\d{4}-\d{2}-\d{2}\.pdf$/);
	});

	it('names a project export after the resolved project', async () => {
		const { projects, service } = setup();
		projects.projects = [projectBuilder({ name: 'Apollo 11' })];
		const result = await service.exportBoardPdf(testActor(), { projectId: testProjectId() });
		expect(result.filename).toMatch(/^kanban-apollo-11-\d{4}-\d{2}-\d{2}\.pdf$/);
	});

	it('titles the document after the resolved project name', async () => {
		const { projects, pdfInputs, service } = setup();
		projects.projects = [projectBuilder({ name: 'Apollo 11' })];
		await service.exportBoardPdf(testActor(), { projectId: testProjectId() });
		expect(pdfInputs[0]?.title).toBe('Apollo 11 todos');
	});

	it('marks each card with its resolved project name', async () => {
		const { todos, projects, markdownSources, service } = setup();
		todos.todos = [todoBuilder()];
		projects.projects = [projectBuilder({ name: 'Apollo 11' })];
		await service.exportBoardPdf(testActor(), {});
		expect(markdownSources[0]).toContain('Apollo 11');
	});
});
