import { drainBeforeTelemetryShutdown, shutdownTelemetry } from './otel-instrumentation.js';
import { registerWebShutdown } from './web-shutdown.js';

registerWebShutdown(process, {
	waitFor: drainBeforeTelemetryShutdown,
	shutdown: shutdownTelemetry
});

// Register the drain before adapter-node starts accepting requests.
// The adapter artifact is generated by pnpm build, not part of the source graph.
await import(new URL('../build/index.js', import.meta.url).href);
